export default {

  AUTH: "AUTH",
  USER_REQUEST: "USER_REQUEST",
  USER_RESPONSE: "USER_RESPONSE",
  USER_ERROR: "USER_ERROR",

  GET_USER_ID: 'GET_USER_ID',
  GET_USER_REQUEST: "CREATE_USER_REQUEST",
  GET_USER_RESPONSE: "CREATE_USER_RESPONSE",
  GET_USER_ERROR: "CREATE_USER_ERROR",

  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
  CREATE_USER_RESPONSE: "CREATE_USER_RESPONSE",
  CREATE_USER_ERROR: "CREATE_USER_ERROR"
};
