export default {

  LOGIN: "LOGIN",
  CURRENT_USER_REQUEST: "CURRENT_USER_REQUEST",
  CURRENT_USER_RESPONSE: "CURRENT_USER_RESPONSE",
  CURRENT_USER_ERROR: "CURRENT_USER_ERROR",

  GET_USER_ID: 'GET_USER_ID',
  GET_USER_REQUEST: "CREATE_USER_REQUEST",
  GET_USER_RESPONSE: "CREATE_USER_RESPONSE",
  GET_USER_ERROR: "CREATE_USER_ERROR",

  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
  CREATE_USER_RESPONSE: "CREATE_USER_RESPONSE",
  CREATE_USER_ERROR: "CREATE_USER_ERROR"
};
